# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/goatzy/Documents/UnrealEngine-5.6/Engine/Unreal_5.6.1

TARGETS = \
	BuildToSurvive-Android-DebugGame  \
	BuildToSurvive-Android-Development  \
	BuildToSurvive-Android-Shipping  \
	BuildToSurvive-Linux-DebugGame  \
	BuildToSurvive-Linux-Development  \
	BuildToSurvive-Linux-Shipping  \
	BuildToSurvive-LinuxArm64-DebugGame  \
	BuildToSurvive-LinuxArm64-Development  \
	BuildToSurvive-LinuxArm64-Shipping  \
	BuildToSurvive \
	BuildToSurviveEditor-Linux-DebugGame  \
	BuildToSurviveEditor-Linux-Development  \
	BuildToSurviveEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend BuildToSurviveEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug BuildToSurviveEditor-Linux-Debug


BuildToSurvive-Android-DebugGame:
	 $(BUILD) BuildToSurvive Android DebugGame  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurvive-Android-Development:
	 $(BUILD) BuildToSurvive Android Development  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurvive-Android-Shipping:
	 $(BUILD) BuildToSurvive Android Shipping  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurvive-Linux-DebugGame:
	 $(BUILD) BuildToSurvive Linux DebugGame  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurvive-Linux-Development:
	 $(BUILD) BuildToSurvive Linux Development  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurvive-Linux-Shipping:
	 $(BUILD) BuildToSurvive Linux Shipping  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurvive-LinuxArm64-DebugGame:
	 $(BUILD) BuildToSurvive LinuxArm64 DebugGame  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurvive-LinuxArm64-Development:
	 $(BUILD) BuildToSurvive LinuxArm64 Development  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurvive-LinuxArm64-Shipping:
	 $(BUILD) BuildToSurvive LinuxArm64 Shipping  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurvive: BuildToSurvive-Linux-Development

BuildToSurviveEditor-Linux-DebugGame:
	 $(BUILD) BuildToSurviveEditor Linux DebugGame  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurviveEditor-Linux-Development:
	 $(BUILD) BuildToSurviveEditor Linux Development  -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" $(ARGS)

BuildToSurviveEditor: BuildToSurviveEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/goatzy/Documents/Unreal Projects/BuildToSurvive/BuildToSurvive.uproject" -Game 

.PHONY: $(TARGETS)
